# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  ranger-admin-password:
    description: |
      Password used for the policy manager (Web interface)
    default: "rangerR0cks!"
    type: string
  tls-secret-name:
    description: |
        Name of the k8s secret which contains the TLS certificate to be used by ingress.
    default: ranger-tls
    type: string
  external-hostname:
    description: |
        The DNS listing used for external connections. 
        Will default to the name of the deployed application.
    type: string
    default: ranger-k8s
  sync-ldap-url:
    description: |
      The url of the ldap to synchronize users from.
      In format `ldap://<host>:<port>`.
    type: string
    default: ldap://comsys-openldap-k8s:389
  sync-ldap-bind-dn:
    description: |
      The bind domain name for ldap synchronization.
    type: string
    default: cn=admin,dc=canonical,dc=dev,dc=com
  sync-ldap-bind-password:
    description: |
        The bind password for ldap synchronization.
    type: string
    default: admin
  sync-ldap-search-base:
    description: |
      Search base for ldap users and groups.
    type: string
    default: dc=canonical,dc=dev,dc=com
  sync-ldap-user-object-class:
    description: |
      The object class corresponding to users for ldapsearch.
    type: string
    default: person
  sync-group-object-class:
    description: |
      The object class corresponding to groups for ldapsearch.
    type: string
    default: posixGroup
  sync-ldap-user-search-base:
    description: |
      Search base for ldap users.
    type: string
    default: dc=canonical,dc=dev,dc=com
  sync-group-user-map-sync-enabled:
    description: |
      Set to true to sync groups without users.
    type: boolean
    default: true
  sync-group-search-enabled:
    description: |
      Set to true to sync groups without users.
    type: boolean
    default: true
  sync-group-search-base:
    description: |
      Search base for ldap groups.
      If not specified this takes the value of `sync-ldap-search-base`.
    type: string
    default: dc=canonical,dc=dev,dc=com
  sync-ldap-user-search-scope:
    description: |
      Search scope for the users.
      Allowed values: `base`, `one` and `sub`.
    type: string
    default: sub
  sync-ldap-group-search-scope:
    description: |
      Search scope for the groups.
      Allowed values: `base`, `one` and `sub`.
    type: string
    default: sub
  sync-ldap-user-search-filter:
    description: |
      Optional additional filter constraining the users selected for syncing.
    type: string
  sync-ldap-user-name-attribute:
    description: |
      Attribute from user entry that would be treated as user name.
    type: string
    default: uid
  sync-group-member-attribute-name:
    description: |
      The attribute in the Group which specifies members.
    type: string
    default: memberUid
  sync-ldap-user-group-name-attribute:
    description: |
      Attribute from user entry whose values would be treated as
      group values to be pushed into Policy Manager database.
    type: string
    default: memberOf
  sync-interval:
    description: |
      The interval in ms to synchronize the users/groups from ldap.
      Note: this can not be less than hourly (3600000) for LDAP.
    type: int
    default: 3600000
  sync-ldap-deltasync:
    description: |
      Enable to incrementally sync as opposed to full sync after initial run.
    type: boolean
    default: true
  ranger-usersync-password:
    description: |
      The password for the Ranger usersync user.
      Must be updated to match in Ranger admin.
    type: string
    default: rangerR0cks!
  policy-mgr-url:
    type: string
    default: http://ranger-k8s:6080
  charm-function:
    description: |
      The function the charm should provide, either `admin` or `usersync`.
    type: string
    default: admin
