# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  ranger-admin-password:
    description: |
      Password used for the policy manager (Web interface)
    default: "rangerR0cks!"
    type: string
