name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      runs-on: "self-hosted-linux-amd64-noble-xlarge"
      channel: 1.35-classic/stable
      provider: k8s
      use-canonical-k8s: true
      extra-arguments: >-
        --kube-config=~/.kube/config
        --juju-controller=localhost-localhost
        --juju-cloud=canonical-k8s
      modules: >-
        ["test_charm.py",
        "test_policy.py",
        "test_scaling.py",
        "test_trino_catalog.py",
        "test_upgrades.py",
        "test_usersync.py"]'
      juju-channel: 3/stable
      trivy-severity-config: CRITICAL
      with-uv: true
