name: Terraform modules tests

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/test_terraform_modules.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-tests:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_test.yaml@main
    secrets: inherit
    permissions:
      contents: read
    with:
      k8s-controller: true
      terraform-directories: '["terraform/charm", "terraform/product"]'
